<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]                #this is a list. Element 0 is Black widow
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_super_names[0]

'Black Widow'

In [3]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])         #This is a numpy array
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

np_real_names[1]              #element 1 of the array

'Tony Stark'

In [9]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
superhero_info["Tony Stark"]    #using the key Tony Stark to call the value Iron Man

'Iron Man'

There are 3 ways of storing data: list, array and dictionary

## 1.1 Let’s compare

In [6]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

## 1.2 Accessing data from a list (or array)

In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [9]:
py_real_names[1]

'Tony Stark'

In [10]:
py_super_names[2]    #element 2 of the list

'Doctor Strange'

In [12]:
py_super_names[-2] #second last element in the list

'Iron Man'

## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [12]:
superhero_info["Tony Stark"]

'Iron Man'

In [16]:
superhero_info.keys()    #list all the keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [17]:
superhero_info.values()    #list all the corresponding values

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [24]:
py_superhero_info[0][1]    #obtain the 2nd value in the 1st element

'Black Widow'

# 2 Lists vs. Arrays

## 2.1 Size

In [26]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [28]:
len(np_array_2d)    #no of elements in array

10

In [29]:
len(py_list_2d)  #no of elements in list

10

In [30]:
np_array_2d.shape    #tells you how many elements(10) there are, and how many values are within each element(2)

(10, 2)

## 2.2 Arrays are fussy about type

In [32]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)
py_list

[1, 1.5, 'A']

In [36]:

np_array    #calling the array. Note that all the int and float are converted to str

array(['1', '1.5', 'A'], dtype='<U32')

In [37]:
py_list    #calling every elements in list. Data types are retained eg 1.5 remains as float

[1, 1.5, 'A']

## 2.3 Adding a number

In [38]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [39]:
py_list + 100   #list does not support math function

TypeError: can only concatenate list (not "int") to list

In [40]:
np_array + 1111110  #arrays allows you to do math manipulation

array([1111111, 1111112, 1111113, 1111114, 1111115])

## 2.4 Adding another list

In [24]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [25]:
py_list_1 + py_list_2   # indiv elements are not added TGT

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [26]:
np_array_1 + np_array_2   #corresponding elements are added tgt

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [43]:
py_list*3 #duplicate list rather than math operation

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [42]:
np_array*2 #math operation instead of duplicating number of elements

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [31]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [44]:
np_array**2    #each element is squared

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [34]:
py_list == 3     #doesnt show ans for each element

False

In [48]:
np_array == 3  #tells me which elements are equals to 3

array([False, False,  True, False, False])

In [47]:
np_array >3     #tells me the position of elements that does not fit this condition

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [50]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [37]:
sum(py_list)     # sum() is a base Python function

15

In [49]:
min(py_list)

1

In [51]:
max(py_list)

5

In [53]:
np_array.mean()

3.0

In [38]:
np_array.sum()

15

In [52]:
np_array.std()

1.4142135623730951

In [40]:
np_array.min()

1

In [41]:
np_array.max()

5

In [43]:
np_array.mode()    #no such rule

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes