<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]


In [5]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

## 1.1 Let’s compare

In [6]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

## 1.2 Accessing data from a list (or array)

In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [9]:
py_real_names[1]

'Tony Stark'

## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [12]:
superhero_info["Tony Stark"]

'Iron Man'

## 1.4 Higher dimensional lists

In [13]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [15]:
len(np_array_2d)

10

In [16]:
len(py_list_2d)

10

## 2.2 Arrays are fussy about type

In [18]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)
py_list

[1, 1.5, 'A']

In [19]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [21]:
py_list + 100

TypeError: can only concatenate list (not "int") to list

In [23]:
np_array + 1111110

array([1111111, 1111112, 1111113, 1111114, 1111115])

## 2.4 Adding another list

In [24]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [25]:
py_list_1 + py_list_2   # indiv elements are not added TGT

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [26]:
np_array_1 + np_array_2   #corresponding elements are added tgt

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [28]:
py_list*2 #duplicate list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [29]:
np_array*2 #math operation

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [31]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [32]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [34]:
py_list == 3     #doesnt show ans for each element

False

In [35]:
np_array == 3  

array([False, False,  True, False, False])

## 2.8 Mathematics

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [37]:
sum(py_list)     # sum() is a base Python function

15

In [38]:
np_array.sum()

15

In [39]:
np_array.sum()

15

In [40]:
np_array.min()

1

In [41]:
np_array.max()

5

In [43]:
np_array.mode()    #no such rule

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes