<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [2]:
import numpy as np

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [3]:
np_array[3]

'd4'

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [5]:
np_array[0]  #first element in the list

'a1'

In [6]:
np_array[-1]  #last element in the list

'j10'

In [8]:
np_array[1:6]     #elements 1 to 5

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [4]:
np_array[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [8]:
np_array[0:5:2]

array(['a1', 'c3', 'e5'], dtype='<U3')

In [10]:
np_array[5:]    #5th element to the end of the list

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [13]:
np_array[::2]  #all element in the list but listed out in multiples of 2

array(['a1', 'c3', 'e5', 'g7', 'i9'], dtype='<U3')

In [12]:
np_array[:5]    #index 0 to 5

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

a1 -> index value 0 OR element 1

## 1.2 Arrays only | Subsetting by masking

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
np_array[my_mask]        #masking values to show those that are more than 3

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[np_array >3/2]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[~(np_array > 3)]                 # '~' = not

array([1, 2, 3])

In [18]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' = and

array([4, 5, 6, 7])

In [19]:
np_array[(np_array < 3) | (np_array > 8)]    # '|' = or

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [23]:
print(py_list_2d[3])
print(np_array_2d[3])    # note that the int 4 is now a str

[4, 'D']
['4' 'D']


In [25]:
print(py_list_2d[3][0])
print(np_array_2d[3],0)     #at index 3, the first value = 4

4
['4' 'D'] 0


In [19]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [20]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [21]:
py_list_2d[:3][0] #gives the entire group in the 1st element

[1, 'A']

In [22]:
np_array_2d[:3, 0]    #gives the 1st value present in all elements

array(['1', '2', '3'], dtype='<U11')

In [23]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [27]:
py_list_2d[3:6][0]      #3:6 is supposed to list everything from element 3 to 6, but the [0] specified it to be the first element of list(element3 to 6), which is just element 3

[4, 'D']

In [29]:
np_array_2d[:, 0]          #first value of each index aka the numbers

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [30]:
x=[1, 2]*3     #this repeats the list thrice
x

[1, 2, 1, 2, 1, 2]

In [32]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
print(x)        #most basic way to append list

x=[1]
x+= [2]
x+= [3]   #slightly more concise as we use the short form +=
x+= [4]
print(x)

x=[1]
x.append(2)   #we immediately append the list to add the numbers 2-4
x.append(3)
x.append(4)
print(x)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]


In [26]:
x=[1, 2, 3]
x.append([4, 5, 6])  #4,5,6 are added tgt as the last element
x

[1, 2, 3, [4, 5, 6]]

In [33]:
x = [1, 2, 3]
x += [4, 5, 6]
x                            #simplest way to append list

[1, 2, 3, 4, 5, 6]

In [28]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x  #this shows the addition of 3 elements

[1, 2, 3, 4, 5, 6]

# Some loose ends

## 1.5 Tuples

In [34]:
a=(1, 2, 3)     # cannot be appended or extended
print(a)

(1, 2, 3)


In [35]:
# The following will NOT work
a[0]=-1
a[0]+= [10]            #it is immutable

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [31]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

print(z)

[1, 2, 3]


In [32]:
z.append([1,2])
print(z)

[1, 2, 3, [1, 2]]


In [33]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes