<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [2]:
import numpy as np

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [3]:
np_array[3]

'd4'

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [4]:
np_array[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [8]:
np_array[0:5:2]

array(['a1', 'c3', 'e5'], dtype='<U3')

In [11]:
np_array[::2]

array(['a1', 'c3', 'e5', 'g7', 'i9'], dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [12]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[np_array >3/2]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [18]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [19]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [20]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [21]:
py_list_2d[:3][0] #gives the entire group in the 1st element

[1, 'A']

In [22]:
np_array_2d[:3, 0]    #gives the 1st value present in all elements

array(['1', '2', '3'], dtype='<U11')

In [23]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

## 1.4 Growing lists

In [25]:
x=[1, 2]*3
x

[1, 2, 1, 2, 1, 2]

In [26]:
x=[1, 2, 3]
x.append([4, 5, 6])  #4,5,6 are added tgt as the last element
x

[1, 2, 3, [4, 5, 6]]

In [28]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x  #this shows the addition of 3 elements

[1, 2, 3, 4, 5, 6]

# Some loose ends

## 1.5 Tuples

In [29]:
a=(1, 2, 3)     # cannot be appended or extended

## 1.6 Be VERY careful when copying

In [31]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

print(z)

[1, 2, 3]


In [32]:
z.append([1,2])
print(z)

[1, 2, 3, [1, 2]]


In [33]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes